Revert "build(deps): bump got from 13.0.0 to 14.0.0 in /docs (#75)" (#76)
This reverts commit 9ad160e7298834cca3358bf17d122fe57fda51da.

Post merge CI fails, with
```
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
warning url-loader@1.1.2: Invalid bin field for "url-loader".
error got@14.0.0: The engine "node" is incompatible with this module. Expected version ">=20". Got "1[6](https://github.com/uber-go/cff/actions/runs/7118151076/job/19380501646#step:4:7).20.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```
reverting.