lint: Use golangci-lint (#56)
Similarly to Zap, switch to using golangci-lint to run linters.
In CI, lint will now run in a separate job than the tests.
This obviates the need for staticcheck in tools/.

Exclusions were added for lint rules that cannot be fixed in generated
code.
Specifically, revive was opted out for generated code in general
because its pedantic style requirements cannot be met easily in
generated code.

<details>
<summary>Lint issues fixed</summary>

```
cmd/cff/main.go:1:1: package-comments: should have a package comment (revive)
internal/aquaregia_test.go:1:1: package-comments: should have a package comment (revive)
internal/buildtag_test.go:224:17: Error return value of `io.WriteString` is not checked (errcheck)
internal/buildtag_test.go:233:17: Error return value of `io.WriteString` is not checked (errcheck)
internal/buildtag_test.go:234:17: Error return value of `io.WriteString` is not checked (errcheck)
internal/emittertest/gen.go:1:1: package-comments: should have a package comment (revive)
internal/flag/flag.go:1:1: package-comments: should have a package comment (revive)
internal/flow_modifier.go:115:2: if-return: redundant if ...; err != nil check, just return error instead. (revive)
internal/gen.go:221:10: Error return value of `w.Write` is not checked (errcheck)
internal/gen.go:226:9: Error return value of `w.Write` is not checked (errcheck)
internal/gen.go:394:13: Error return value of `format.Node` is not checked (errcheck)
internal/gendirectives/main.go:64:17: Error return value of `out.Close` is not checked (errcheck)
internal/gendirectives/main_test.go:15:20: Error return value of `os.RemoveAll` is not checked (errcheck)
internal/gendirectives/main_test.go:53:20: Error return value of `os.RemoveAll` is not checked (errcheck)
internal/modifier/concurrency.go:1:1: package-comments: should have a package comment (revive)
internal/modifier/concurrency.go:44:2: if-return: redundant if ...; err != nil check, just return error instead. (revive)
internal/modifier/factory.go:86:2: if-return: redundant if ...; err != nil check, just return error instead. (revive)
internal/pkg/gopackages.go:1:1: package-comments: should have a package comment (revive)
scheduler/scheduler_test.go:208:22: Error return value of `blocker.Run` is not checked (errcheck)
scheduler/scheduler_test.go:268:22: Error return value of `blocker.Run` is not checked (errcheck)
```

</details>